parameters:
    database_driver:   pdo_sqlsrv
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     SistInfo
    database_user:     sistinfo
    database_password: sistinfo77

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
