usuario_login:
    pattern:   /login
    defaults:   { _controller: FrontendBundle:Default:login }

usuario_login_check:
    pattern:   /login_check

usuario_logout:
    pattern:   /logout

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
