<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoletaRecepcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletaRecepcionRepository extends EntityRepository
{
    public function buscarBoletasRecepcion($criteria)
    {
        $qb = $this->createQueryBuilder("b");
        foreach ($criteria as $field => $value) {
            if (!$this->getClassMetadata()->hasField($field)) {
                continue;
            }
            if(!empty($value)) {
                if(in_array($field, ['fecha_ingreso', 'fecha_salida'] )) {
                    
                    $date = $value->format('Y-m-d');
                    $nextDayDate = date('Y-m-d', strtotime('+1 day', strtotime($date)));
                    
                    $qb ->andWhere($qb->expr()->gte('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, $value);
                    $qb ->andWhere($qb->expr()->lt('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, new \DateTime(strtotime($nextDayDate)));
                    
                }
                else {
                    $qb ->andWhere($qb->expr()->eq('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, $value);
                }
                
            }
        }
        return $qb->getQuery()->getResult();
    }
}
