<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciaRepository extends EntityRepository
{
    public function buscarIncidencia($criteria)
    {
        $qb = $this->createQueryBuilder("b");
        foreach ($criteria as $field => $value) {
            if (!$this->getClassMetadata()->hasField($field)) {
                continue;
            }
            if(!empty($value)) {
                if(in_array($field, ['fecha_incidencia'] )) {
                    
                    $date = $value->format('Y-m-d');
                    $nextDayDate = date('Y-m-d', strtotime('+1 day', strtotime($date)));
                    
                    $qb ->andWhere($qb->expr()->gte('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, $value);
                    $qb ->andWhere($qb->expr()->lt('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, new \DateTime(strtotime($nextDayDate)));
                    
                }
                else {
                    $qb ->andWhere($qb->expr()->eq('b.'.$field, ':b_'.$field))
                    ->setParameter('b_'.$field, $value);
                }
                
            }
        }
        return $qb->getQuery()->getResult();
    }
    
    public function buscarIncidenciasPorFecha($fechaInicio, $fechaFin)
    {
       $qb = $this->createQueryBuilder("b");
        $fechaIncidencia = 'fecha_incidencia';
        $qb ->where($qb->expr()->gte('b.'.$fechaIncidencia, ':b_'.'fecha_inicio'))
                    ->setParameter('b_'.'fecha_inicio', $fechaInicio);
        $qb ->andWhere($qb->expr()->lte('b.'.$fechaIncidencia, ':b_'.'fecha_fin'))
                    ->setParameter('b_'.'fecha_fin', $fechaFin);
        
       return $qb->getQuery()->getResult(); 
    }
}
