<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoDetalleRepository extends EntityRepository
{
    public function buscarPedidos($pedidos)
    {
        $pedidosConDetalle = [];
        foreach($pedidos as $pedido) {
            $pedidoDetalle = $this->findOneBy(['pedido' => $pedido]);
            $pedidosConDetalle[] = ['id' => $pedido->getId(),
                'fechaProgramacion' => $pedido->getFechaProgramacion(),
                'estado' => $pedido->getEstado(),
                'material' => $pedidoDetalle->getMaterial(),
                'cantidad' => $pedidoDetalle->getCantidad()];
        }
        return $pedidosConDetalle;
        
    }
}
