<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    public function buscarPedidos($criteria)
    {
        $qb = $this->createQueryBuilder("p");
        
        foreach ($criteria as $field => $value) {
            if (!$this->getClassMetadata()->hasField($field)) {
                continue;
            }
            if(!empty($value)) {
                
                    $qb ->andWhere($qb->expr()->eq('p.'.$field, ':p_'.$field))
                    ->setParameter('p_'.$field, $value);
            }
        }
        return $qb->getQuery()->getResult();
    }
    
    
    public function buscarPedidosConfirmados($criteria)
    {
     $qb = $this->createQueryBuilder("p");
        
        foreach ($criteria as $field => $value) {
            if (!$this->getClassMetadata()->hasField($field)) {
                continue;
            }
            if(!empty($value)) {
                
                    $qb ->andWhere($qb->expr()->eq('p.'.$field, ':p_'.$field))
                    ->setParameter('p_'.$field, $value);
            }
        }
        $qb->andWhere($qb->expr()->eq('p.estado', ':p_estado'))
                ->setParameter(':p_estado', 5);
        return $qb->getQuery()->getResult();   
    }
    
    public function buscarPedidosPendientesPorFecha($clienteId, $fechaInicio, $fechaFin, $pendiente)
    {
        $qb = $this->createQueryBuilder("p");
        
        $qb ->andWhere($qb->expr()->gt('p.fecha_programacion', ':p_fecha_inicio'))
                ->setParameter('p_fecha_inicio', $fechaInicio)
            ->andWhere($qb->expr()->lt('p.fecha_programacion', ':p_fecha_fin'))
                ->setParameter('p_fecha_fin', $fechaFin)
            ->andWhere($qb->expr()->eq('p.estado', ':p_estado'))
                ->setParameter('p_estado', $pendiente);
        
        
        if($clienteId != "") {
            $qb->andWhere($qb->expr()->eq('p.cliente', ':p_cliente'))
                ->setParameter('p_cliente', $clienteId);
        }
        
        return $qb->getQuery()->getResult();
    }
            
    public function buscarPedidosPorFecha($clienteId, $fechaInicio, $fechaFin)
    {
        $qb = $this->createQueryBuilder("p");
        
        $qb ->andWhere($qb->expr()->gt('p.fecha_programacion', ':p_fecha_inicio'))
                ->setParameter('p_fecha_inicio', $fechaInicio)
            ->andWhere($qb->expr()->lt('p.fecha_programacion', ':p_fecha_fin'))
                ->setParameter('p_fecha_fin', $fechaFin);
        
        if($clienteId != "") {
            $qb->andWhere($qb->expr()->eq('p.cliente', ':p_cliente'))
                ->setParameter('p_cliente', $clienteId);
        }
        
        return $qb->getQuery()->getResult();
    }
    
    
}
