<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoletaMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepcionMaterialRepository extends EntityRepository
{
    public function getUltimasRecepcionMateriales($numeroRecepcionMateriales)
    {
        return $this->findBy([], ['id' => 'DESC'], $numeroRecepcionMateriales);
    }
    
    public function getRecepcionMaterialesPorBoletaRecepcionId($boletaRecepcionId)
    {
        return $this->findBy(['boleta_recepcion' => $boletaRecepcionId],
                ['id' => 'DESC']);
    }
}
