<?php

namespace Sistema\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadMedidaRepository extends EntityRepository
{
    public function getUnidadMedidaTonelada()
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('um')
                ->from('FrontendBundle:UnidadMedida', 'um')
                ->add('where', $queryBuilder->expr()->eq('um.nombre', ':nombre'))
                ->setParameter('nombre', 'TN');
        return $queryBuilder;
    }
}
